# Generated by Django 4.0.2 on 2022-07-14 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_app_app1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App1',
            new_name='Article',
        ),
    ]
