# Generated by Django 4.0.2 on 2022-07-17 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_app1_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='createdate'),
            preserve_default=False,
        ),
    ]
