# Generated by Django 4.0.2 on 2022-07-19 20:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='explanation',
            field=ckeditor.fields.RichTextField(verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Mətn adi'),
        ),
    ]
